import time
from OxfordMagLab2000.General import Manager
from OxfordMagLab2000.OxfordCryostat import OxfordILM

rm = Manager.Manager()
ILM = OxfordILM.OxfordILM(rm, GPIB_adress='GPIB0::25::INSTR', ISOBUS_master=False, ISOBUS_linked=True, ISOBUS_adress=5)
print(ILM.identity)
print(ILM.last_queried_status)
print(ILM.last_decodified_status)
print(ILM.channel_1_level)
print(ILM.channel_2_level)
print(ILM.channel_3_level)
print(ILM.needle_valve_position)
ILM.set_channel_1_level_display()
time.sleep(10)
ILM.set_channel_2_level_display()
time.sleep(10)
ILM.set_channel_3_level_display()
time.sleep(10)
ILM.set_needle_valve_position_display()
time.sleep(10)
ILM.set_needle_valve_position(25)
print(ILM.needle_valve_position)
time.sleep(10)
ILM.set_needle_valve_position(50)
print(ILM.needle_valve_position)
ILM.set_channel_1_level_display()
ILM.set_helium_channel_to_fast(1)
print(ILM.last_queried_status)
print(ILM.last_decodified_status)
print(ILM.channel_1_level)
time.sleep(10)
print(ILM.last_queried_status)
print(ILM.last_decodified_status)
print(ILM.channel_1_level)
ILM.set_helium_channel_to_slow(1)
print(ILM.last_queried_status)
print(ILM.last_decodified_status)
print(ILM.channel_1_level)
ILM.close()